### ISSUE TITLE
Is someone allowed to create a project when not logged in?

### ISSUE THREAD

**Issue by jingjingwang** [DemocracyLab/CivicTechExchange#1]
Right now "projects/signup" is accessible without being logged in. (We will get an error if click on "submit" though)

**Comment by marlonkeating** [comment]
Yes, even though the 'ADD A PROJECT' link isn't visible when users aren't logged in, the url is still accessible.  Ideally, we'll want to redirect to the login page, which will forward to the Add Project page.
