### ISSUE TITLE
Restrict volunteering with project to only listed roles

### ISSUE THREAD

**Issue by marlonkeating** [DemocracyLab/CivicTechExchange#1014]
Due to user feedback, we would like to restrict users from volunteering for projects with roles that aren't currently listed on the project.

## Background discussions
https://github.com/DemocracyLab/CivicTechExchange/issues/938

## Acceptance Criteria
- Do not show 'Volunteer with Project' button on project profile if the project has no open roles
- For a project with roles, upon clicking 'Volunteer with Project', do not list the 'Other' option (which currently lets them select any role)

## Code Locations
[Volunteer with Project Button](https://github.com/DemocracyLab/CivicTechExchange/blob/2667ae0c3dfc9f344a4d009f1cc894930e5417f9/common/components/common/projects/ProjectVolunteerButton.jsx#L153)

['Other' role option to remove](https://github.com/DemocracyLab/CivicTechExchange/blob/2667ae0c3dfc9f344a4d009f1cc894930e5417f9/common/components/common/projects/ProjectVolunteerModal.jsx#L47)

**Comment by qchiujunhao** [comment]
Completed by PR #1023
