### ISSUE TITLE
CSP_FRAME for Iframe embedding of dlab groups and projects

### ISSUE THREAD

**Issue by ddfridley** [DemocracyLab/CivicTechExchange#1015]
With the new iframe feature #978, we need to set the CSP_FRAME_SRC and CSP_FRAME_ANCESTORS environment variables manually on the server.

We need to automate it, so the people using the feature input the data and we don't have to do it manually.

I have two proposals for how:

1. Create a new CSP_FRAME link that someone could add to their project or group "Resources".

<img width="960" alt="image" src="https://github.com/DemocracyLab/CivicTechExchange/assets/3317487/8b06c7f5-43d4-4c98-9474-2ab6d85ad30f">

One drawback of this is that it makes the CSP_FRAME link for a group/project visible to users. It's not a security issue, just a distraction.

2. Alternatively, would could make CSP_FRAME a parameter on the group and project page:
<img width="960" alt="image" src="https://github.com/DemocracyLab/CivicTechExchange/assets/3317487/d7de8231-1ba2-421e-ac8d-9d7a27e36ca7">

This would make sense on the group page, but on a project there would be a lot of projects that wouldn't use this parameter.

But in this way it would not be visible to general volunteers where it's kind of a distraction.

3. Other ideas?

Additional requirements in either case:

- [ ] when someone makes an update to their group, or project, and makes a change to the this value, we would update the CSP_FRAME_SRC and CSP_FRAME_ANCESTORS variables in python accordingly, adding, updating or deleting the domain name.

- [ ] On startup, we would read all the CSP_FRAME values out of the database and update the python CSP_FRAME_SRC and CSP_FRAME_ANCESTORS variables.

Technical note:
The CSP_FRAME_SRC and CSP_FRAME_ANCESTORS values in the server are comma separated strings for domain names. For example: '["qiqochat.com", "*.qiqochat.com", "*.google.com", "*.youtube.com", "democracylab.org", "democracy-lab-prod-mirror.herokuapp.com", "democracy-lab-dev.herokuapp.com", "democracy-lab-staging.herokuapp.com"]'
We need to add the CSP_FRAME parameters to these lists, in the proper format.

**Comment by PeterBreen** [comment]
Closing this for now to clean up our open issues for the sake of other volunteers; we can reopen this when needed at a future time but it's premature at this stage.
