### ISSUE TITLE
Sign in/Sign up page still visible after successful sign in

### ISSUE THREAD

**Issue by DevEsteves** [DemocracyLab/CivicTechExchange#1050]
![image](https://github.com/DemocracyLab/CivicTechExchange/assets/54783087/6be6d0a4-5002-414b-b5af-f221903961b2)

After logging in, I can still see the sign in/sign up page, 

I think it would be nice to have a condition for the sign in/sign up page to no longer appear and or a automatic redirection for the home page.

**Comment by PeterBreen** [comment]
This looks pretty similar to #1016 - is there something not covered in that issue (or #1020, the PR to fix it) that we should add?

**Comment by DevEsteves** [comment]
> This looks pretty similar to #1016 - is there something not covered in that issue (or #1020, the PR to fix it) that we should add?

Sorry, I didn't see these two issues.  I'll try to take that issue.

**Comment by PeterBreen** [comment]
It's no problem. I'll close this as a duplicate, but thanks for spotting the issue. I'm working on trying to clean up our open issues/PRs to make it easier - we have a lot, I know!
