### ISSUE TITLE
Review tag import

### ISSUE THREAD

**Issue by themightychris** [DemocracyLab/CivicTechExchange#261]
Hey DemocracyLab!

As part of an effort to survey all the civic tech taxonomies out there and start building tooling to connect them together, I've imported your tag definitions into a versioned format we can keep pulling: https://github.com/codeforamerica/civic-tech-taxonomy/tree/sites/democracylab.org

If there's a better way to grab your latest tag data, please open a pull request against this code: https://github.com/codeforamerica/civic-tech-taxonomy/blob/master/import.js#L187

See notes on what I just did here: https://github.com/codeforamerica/brigade-project-index/issues/9#issuecomment-518055563

**Comment by themightychris** [comment]
Take a look at this issue too, it would be a great place to get some feedback from the DemocracyLab team: https://github.com/codeforamerica/brigade-project-index/issues/26

**Comment by themightychris** [comment]
@marlonkeating @mfrischmuth ^

**Comment by PeterBreen** [comment]
The canonical location for our tag data is here: https://github.com/DemocracyLab/CivicTechExchange/blob/master/common/models/Tag_definitions.csv

This may change but not in the short term (obviously, as I'm closing a 4 year old issue) but we want to do some work with tags that allow greater flexibility for both dlab admins and dlab project owners.
