### ISSUE TITLE
Inactive Slack link: README.md and CONTRIBUTING.md

### ISSUE THREAD

**Issue by aminamos** [DemocracyLab/CivicTechExchange#316]
Slack invite hyperlinks in README.md and CONTRIBUTING.md lead to an inactive destination, but the Slack invite from https://www.democracylab.org/index/?section=AboutProject&id=1 is valid.

**Comment by PeterBreen** [comment]
Thanks for letting us know! As you can see I've put in a PR to update our documentation. Please let me know if the invite links in the docs work properly once we merge that in. :)
