### ISSUE TITLE
Feature Request: Scan more branches than just master

### ISSUE THREAD

**Issue by JacksonMaxfield** [DemocracyLab/CivicTechExchange#389]
I love the fact that DemocracyLab now updates projects based off of GitHub activity. Unfortunately, a bunch of our work is targeted at future `release-*` branches (see [here](https://github.com/CouncilDataProject/cdptools/tree/release-3)). It would be great to simply updated based off any branch push.

**Comment by marlonkeating** [comment]
Looking into the github API, I haven't found a good way to scan for recently-updated branches without querying every branch individually.  Would it work for you to specify a branch link in your project profile (e.g. https://github.com/CouncilDataProject/cdptools/tree/release-3), that could be scanned along with the rest of your github links?

**Comment by JacksonMaxfield** [comment]
Yeah I would be fine with adding specific branches to scan.

**Comment by marlonkeating** [comment]
Resolved by #642, and now deployed to production site as of [v0.21.6.2](https://github.com/DemocracyLab/CivicTechExchange/releases/tag/v0.21.6.2)
