### ISSUE TITLE
Loading test fixtures fails due to duplicate entries

### ISSUE THREAD

**Issue by whitbur** [DemocracyLab/CivicTechExchange#404]
When loading test fixtures with `python manage.py loaddata testdata.json`, the following error consistently appears:
```bash
root@f68fb218ac5f:/code# python manage.py loaddata testdata.json
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "common_tag_tag_name_key"
DETAIL:  Key (tag_name)=(sketch) already exists.
```
This error still occurs directly after running `python manage.py flush`, indicating something other than the fixtures is populating this table. I was able to trace the code to [these lines in common/apps.py](https://github.com/DemocracyLab/CivicTechExchange/blob/master/common/apps.py#L11-L13), which populate the tags from a csv before the fixtures are loaded, causing the duplicates.

Commenting out these lines allows us to move past this error, but will likely cause issues elsewhere. A long term fix should be pursued that allows test fixtures to be loaded after flushing the database.

I also ran into further duplicate errors while loading the test data:
```bash
root@f68fb218ac5f:/code# python manage.py loaddata testdata.json
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "django_content_type_app_label_model_76bd3d3b_uniq"
DETAIL:  Key (app_label, model)=(civictechprojects, project) already exists.
```
It appears that `python manage.py flush` doesn't clear the `django_content_type` table, likely due to the foreign key constraint in the `auth_permission` table which it also doesn't clear (perhaps intentionally? I'm not a django expert). Manually clearing those tables allowed me to fully load the test data without issue. I cleared the tables using the postgresql command line:
```
postgres=# delete from auth_permission;
DELETE 105
postgres=# delete from django_content_type;
DELETE 35
```
I am using Docker as my development environment, on Ubuntu 20.04 LTS.

### Steps to Reproduce
1. Check out git repository, `mainline` branch (currently at ec4dca12)
2. Run `docker-compose build` and wait for the image to build.
3. Run `docker-compose up -d` and wait for containers to launch
4. Validate that the dev server successfully runs localhost:8000
5. Validate that the dev-admin login doesn't work at /admin (missing fixtures)
6. Run `docker-compose exec web python manage.py flush --noinput` to clear the database
7. Run `docker-compose exec web python manage.py loaddata testdata.json` to see the error.

**Comment by marlonkeating** [comment]
Fixed as part of #407
