### ISSUE TITLE
Add hackathon image to homepage rotation

### ISSUE THREAD

**Issue by glenbraun** [DemocracyLab/CivicTechExchange#464]
Our homepage splash image rotates, and we'd like to add an image to the rotation:
https://d1agxr2dqkgkuy.cloudfront.net/img/CodeForGood_072719_MSReactor-003.jpg

https://github.com/DemocracyLab/CivicTechExchange/blob/00296f1762d840ec82806533c5a002308d6f5517/common/components/componentsBySection/FindProjects/SplashScreen.jsx

https://trello.com/c/4HYCs3n6

**Comment by zh-zhang916** [comment]
I am not sure how this background-image URL gets added to the correct HTML element, but I believe this will do the work.

<img width="685" alt="Screen Shot 2021-05-11 at 5 56 51 PM" src="https://user-images.githubusercontent.com/42627607/117903313-2a4c4200-b284-11eb-86de-783534cc389d.png">
