### ISSUE TITLE
Volunteer Profile: Job experience

### ISSUE THREAD

**Issue by glenbraun** [DemocracyLab/CivicTechExchange#467]
https://trello.com/c/cTk42EXM/114-volunteer-profile-page
https://google-drive.trello.services/authorize-link.html#
https://trello.com/c/XKnEfhVY/407-volunteer-profile-job-experience

**Comment by PeterBreen** [comment]
Reviewing this issue to see if Volunteer Activity Reporting (VAR) or similar design has superseded it.

**Comment by PeterBreen** [comment]
The user profile page has seen an update since this issue came out, so I'm closing it as stale. I'm checking with our design lead on whether or not there's new updates in the pipeline but those'll be separate tickets.
