### ISSUE TITLE
OAuth: Store user photos on DemocracyLab CDN

### ISSUE THREAD

**Issue by glenbraun** [DemocracyLab/CivicTechExchange#470]
For accounts created with an OAuth login, we do not appear to store the user's avatar image on DemocracyLab's side; we just link to it on its original hosted location (LinkedIn, etc).

This means we are potentially loading a lot of third party content on any list of project volunteers and/or running into third-party content restrictions: Firefox automatically blocks LinkedIn-hosted avatars under their third-party tracking prevention rules, for example.

There's no way for a user to detect or fix this problem happening for someone else, so let's be consistent in storing user avatars on our CDN.

[https://trello.com/c/JpHag5YK](url)

Related: [https://trello.com/c/T5Vzn3ur](url)

<img width="871" alt="Screen_Shot_2020-02-10_at_12 26 56_PM" src="https://user-images.githubusercontent.com/5191966/100660994-a7ec4900-3307-11eb-8101-ed4deb75c6b5.png">

**Peter Breen Feb 10 at 12:31 PM (edited)**
[https://trello-attachments.s3.amazonaws.com/5ad79583b33b44863081a406/5dd818e87116d4781985e40c/b421ea68db53ce7035c6676d3df1fb17/Screen_Shot_2020-02-10_at_12.26.56_PM.png](url)
Screen Shot 2020-02-10 at 12.26.56 PM.png Left to right, a default avatar, a LinkedIn avatar not allowing us to hotlink (403 forbidden) and a linkedIn avatar allowing us to hotlink.

Not sure why yet but I replicated this in Safari and Chrome, so my previous belief avatars not showing up was only due to Firefox's anti-tracking is no longer accurate.

**Comment by marlonkeating** [comment]
Fixed as part of #505
