### ISSUE TITLE
Github Updates: Ingest branches other than master

### ISSUE THREAD

**Issue by glenbraun** [DemocracyLab/CivicTechExchange#473]
If projects want to specify branches other than master for us to track for project updates, they should be able to do so by adding branch links to their project profile.

Get branches:
https://developer.github.com/v3/repos/branches/#list-branches

**Marlon Keating Jun 29 at 1:07 PM**
Related: https://github.com/DemocracyLab/CivicTechExchange/issues/389

https://trello.com/c/qYuYCJmU

**Comment by bhg** [comment]
[Pull request](https://github.com/DemocracyLab/CivicTechExchange/pull/642)
