### ISSUE TITLE
Fix Bad Legacy Location data

### ISSUE THREAD

**Issue by glenbraun** [DemocracyLab/CivicTechExchange#475]
Back when we first launched DemocracyLab, we let projects enter in any location they wanted. As a result, some old project still have these old locations and aren't able to be searched for via location filters.

id project_name project_location project_city
62 Zelos.ai Seattle WA
63 The National Student Vote Seattle WA.
61 eLiberate / Public Sphere Project Seattle
7 Northwest Health Career Path - Diversity in Health Sciences Seattle

**Checklist**
- [ ] Update project_location entries for affected projects to be 'Seattle, WA'

- [ ] Run 'python manage.py data_migrations migrate_location' to populate Seattle metadata

**Comment by marlonkeating** [comment]
These corrections are easily made through the admin interface, so we will do it there rather than through a code change.
