### ISSUE TITLE
My Groups\My Projects page expanded view

### ISSUE THREAD

**Issue by glenbraun** [DemocracyLab/CivicTechExchange#479]
We want to show an expanded view of users' groups/projects.

[Figma: My Groups design](https://www.figma.com/file/WADcmVjJh5ARVoZ09xlpfdFN/DemocracyLab?node-id=7904%3A10534)

[Figma: My Projects design](https://www.figma.com/file/WADcmVjJh5ARVoZ09xlpfdFN/DemocracyLab?node-id=643%3A0)

https://trello.com/c/jaLrJD0x

**Comment by PeterBreen** [comment]
The associated designs have been archived (?) or lost; they're old enough at this point we can create a new issue if/when redesigns of those pages are redone by design.
