### ISSUE TITLE
Bug: Users can delete name from their profile

### ISSUE THREAD

**Issue by glenbraun** [DemocracyLab/CivicTechExchange#480]
We require new users to enter a first and last name, but once they're signed up there's currently nothing preventing them from erasing their first/last names from the Edit profile page.

https://trello.com/c/MXyGONJ2

**Comment by DrPoppyseed** [comment]
Hi @glenbraun , is it ok if I give it a crack at it? I'm not familiar with django, but if it's just front-end validation, I think I can tackle the issue.

**Comment by marlonkeating** [comment]
A pure front-end fix is fine for this.

**Comment by marlonkeating** [comment]
No longer an issue
