### ISSUE TITLE
SEO: Use og:url tag

### ISSUE THREAD

**Issue by glenbraun** [DemocracyLab/CivicTechExchange#489]
from https://ogp.me/:
og:url - The canonical URL of your object that will be used as its permanent ID in the graph, e.g., "https://www.imdb.com/title/tt0117500/".

[Trello Card](https://trello.com/c/afpHwPy9)

**Comment by marlonkeating** [comment]
Should be very simple to add now that we are populating rel=canonical links.
https://github.com/DemocracyLab/CivicTechExchange/blob/9e419d9a2436f0768d0008e676bc41a5f0620129/civictechprojects/templates/new_index.html#L21

**Comment by marlonkeating** [comment]
Closed as part of #716
