### ISSUE TITLE
Investigate enabling server-side compression (gzip)

### ISSUE THREAD

**Issue by glenbraun** [DemocracyLab/CivicTechExchange#491]
Instead of sending uncompressed HTML, CSS, or JS to the end user, enabling gzip or deflate or similar on the server end lets us reduce total bytes transferred before the page renders to browsers which request it (most modern ones do by default). We should investigate how to best do this, if feasible.

https://stackoverflow.com/questions/16691506/what-is-gzip-compression
https://docs.djangoproject.com/en/2.1/ref/middleware/#module-django.middleware.gzip (check and see if BREACH has been mitigated in our version of Django)

**Peter Breen Sep 17 at 11:09 AM**
https://devcenter.heroku.com/articles/compressing-http-messages-with-gzip

[Trello Card](https://trello.com/c/6NU3r6cg)

**Comment by fazlu** [comment]
I haven't come across confirmation/documentation to indicate GZIP support (Django 3.1) has mitigated the Breach vulnerability.

The Django documentation (version in use in CivicTechExchange) maintains the warning relating to the use of GZIP:
https://docs.djangoproject.com/en/3.1/ref/middleware/

**Comment by marlonkeating** [comment]
@fazlu, there are at least a couple 3rd party middleware packages that try to address the BREACH issue.
https://github.com/lpomfrey/django-debreach
https://github.com/wnyc/breach_buster

Also, we have put SAMESITE mitigations in place to prevent cross-origin requests that haven't been whitelisted from known partners, which some say is the best way to mitigate BREACH attacks.  It's possible we may not need to worry about BREACH attacks.
https://www.sjoerdlangkemper.nl/2016/04/14/preventing-csrf-with-samesite-cookie-attribute/

**Comment by fazlu** [comment]
Gzip server side compression & django debreach functionality has been enabled & committed to branch "fazlu/feature/issue-491"

Post implementation testing confirms the page content is being served with gzip compression.

**Comment by marlonkeating** [comment]
Addressed by #619
