### ISSUE TITLE
Update Heroku buildpack to enable PostGIS features

### ISSUE THREAD

**Issue by glenbraun** [DemocracyLab/CivicTechExchange#492]
Currently we use the heroku flag BUILD_WITH_GEO_LIBRARIES to include PostGIS library support, but it has been deprecated and we should move to using a new buildpack that includes the libraries.

Heroku Message:
The GDAL, GEOS and PROJ binaries and BUILD_WITH_GEO_LIBRARIES functonality are now deprecated.
! An alternative buildpack to enable GDAL, GEOS and PROJ use is available here - https://github.com/heroku/heroku-geo-buildpack

[Trello Card](https://trello.com/c/HVJ1n9EX)

**Comment by marlonkeating** [comment]
This issue was resolved on the heroku side
