### ISSUE TITLE
Create Project Typo: "Describe the actions that need to be token"

### ISSUE THREAD

**Issue by marlonkeating** [DemocracyLab/CivicTechExchange#508]
In the 'Actions' field of the Create Projects page, the placeholder text reads "Describe the actions that need to be token", when it should be "taken".

![image](https://user-images.githubusercontent.com/322346/101555160-e79cdb80-396c-11eb-86cb-0c27f861bd87.png)

**Comment by DrPoppyseed** [comment]
Hi, if the issue is still open and no one has claimed it yet, is it ok if I address this? It'll be my very first contribution to open source projects.

**Comment by marlonkeating** [comment]
@DrPoppyseed Go right ahead!
