### ISSUE TITLE
Project Profile: Organization type text should break on words, not characters

### ISSUE THREAD

**Issue by marlonkeating** [DemocracyLab/CivicTechExchange#519]
The text for the Organization Type field on the project profile page breaks on characters, which makes for an awkward presentation.

![image](https://user-images.githubusercontent.com/322346/103805531-8ff39d80-5008-11eb-985f-66e09b21b438.png)

**Comment by PeterBreen** [comment]
This is controlled in the `ProjectDetails.jsx` component, https://github.com/DemocracyLab/CivicTechExchange/blob/7b4c6323e87d2fc74994148881321d8a0bb29c38/common/components/componentsBySection/FindProjects/ProjectDetails.jsx#L53-L58

We want to retain existing behavior for the rest of the project details, so adding a specific solution for just Organization Type is best. Conveniently, Bootstrap (which we already use) provides the `text-break` class which will do the job without having to write more custom CSS.

To solve this issue, in ProjectDetails.jsx, change
`<p className="AboutProjects-icon-text">{this.state.projectOrganizationType}</p>` 
to 
`<p className="AboutProjects-icon-text text-break">{this.state.projectOrganizationType}</p>`

**Comment by AshtarCodes** [comment]
Hi, I'd like to work on this issue if it's still available. Thank you!

**Comment by PeterBreen** [comment]
> 
> 
> Hi, I'd like to work on this issue if it's still available. Thank you!

It is. The file hasn't had any new commits since we added the issue. A live example can be found on any page with that organization type, e.g. https://democracylab.org/projects/81
