### ISSUE TITLE
Partner with Us Page: Content doesn't fit on 320px mobile view

### ISSUE THREAD

**Issue by marlonkeating** [DemocracyLab/CivicTechExchange#528]
At 320px width, some of the text extends outside the viewport on the Partner With Us page.

![image](https://user-images.githubusercontent.com/322346/105567814-b6dcef80-5ce9-11eb-80ed-d27d14a3f654.png)

**Comment by PeterBreen** [comment]
Specifically, this is due to the logo images having a `min-width: 300px` applied at this viewport size; that rule has importance at a larger viewport but should be removed here. At 320px viewport, the available container width is about 260px, so that forced minimum breaks the container.

**Comment by AshtarCodes** [comment]
Hi, Is this issue still available? I'd be happy to work on this! Thanks

**Comment by PeterBreen** [comment]
> 
> 
> Hi, Is this issue still available? I'd be happy to work on this! Thanks

Hi, yes, it is. You can see it on the live site here: https://democracylab.org/about/partner using either a 320px width device or devtools emulating it.

**Comment by marlonkeating** [comment]
The Partner With Us page has been retired
