### ISSUE TITLE
Login Page: Sign In button is greyed out if browser auto-populates user name and password

### ISSUE THREAD

**Issue by marlonkeating** [DemocracyLab/CivicTechExchange#535]
When a browser saves the user name and password and populates it upon navigating to the Login page, the Sign In button is greyed out until some user input is made.

**Comment by PeterBreen** [comment]
This appears to be a somewhat-common issue with browser autofill; there's some inconsistency with that across browsers so I'll have to investigate how we can solve it without relying on browsers firing a change event (which some but not all do upon autofill) 

see e.g. this question on SO which has some truly wild methods of detection: https://stackoverflow.com/questions/11708092/detecting-browser-autofill
