### ISSUE TITLE
My Projects Page: Volunteer applicants should have their status listed as 'Pending'

### ISSUE THREAD

**Issue by marlonkeating** [DemocracyLab/CivicTechExchange#542]
On the My Projects page, we currently list volunteers as 'Active' when they apply to a project, even though they haven't been approved by a project owner yet.  Prior to that approval, we should list them as 'Pending' instead.

**Comment by nighthawkEnterprise** [comment]
Hi Marlon, 
     Is there an API sheet that shows us what to hit, and what the possible responses could be? Is one of the responses pending?

**Comment by marlonkeating** [comment]
MyProject api schema: https://github.com/DemocracyLab/CivicTechExchange/blob/b94e5a0c5d6bb6e48113d603ed10f0305a3afd9c/common/components/stores/MyProjectsStore.js#L12

Where to make change:
https://github.com/DemocracyLab/CivicTechExchange/blob/b94e5a0c5d6bb6e48113d603ed10f0305a3afd9c/common/components/componentsBySection/MyProjects/MyProjectCard.jsx#L63
