### ISSUE TITLE
Update test_views unit test for django 3

### ISSUE THREAD

**Issue by marlonkeating** [DemocracyLab/CivicTechExchange#572]
Since the upgrade to django 3, the test_views unit tests have been failing.  The AutoFixture helper class uses a deprecated library (django.utils.six), and so a replacement or update for AutoFixture will need to be found.

https://github.com/DemocracyLab/CivicTechExchange/blob/6990017f2c6a96c8d521eece46a3ca0671867f22/civictechprojects/tests/test_views.py

**Comment by PeterBreen** [comment]
The [Django 3.0 release notes](https://docs.djangoproject.com/en/3.0/releases/3.0/#removed-private-python-2-compatibility-apis) provide some context on why django.utils.six was removed.
