### ISSUE TITLE
OAuth: Don't publish users to Qiqochat until they have entered name

### ISSUE THREAD

**Issue by marlonkeating** [DemocracyLab/CivicTechExchange#579]
Since we have added support for letting users sign up with OAuth accounts that do not have names, we will need to make sure that we don't create accounts in Qiqochat until the user enters their name.

https://github.com/DemocracyLab/CivicTechExchange/blob/8dd76e4b687409f399ecbf8f92b368b9bb5a920d/common/helpers/qiqo_chat.py#L22-L23

**Comment by zh-zhang916** [comment]
I was looking around the web in order to find where we are using Qiqochat, but that doesn't work out. Is there a way for me to replicate this issue?

**Comment by marlonkeating** [comment]
The easiest way to replicate the issue that I know of is to

- Go to your [github profile](https://github.com/settings/profile) and remove your first and last name
- Sign into site using github
- You will be prompted to add your first/last name at this point
