### ISSUE TITLE
Valid project URL path with invalid arguments should show page with canonical url

### ISSUE THREAD

**Issue by marlonkeating** [DemocracyLab/CivicTechExchange#603]
In our logs we regularly see malformed project urls that are an amalgamation of our old url scheme and our new url scheme.
Example:
/projects/497?section=AboutProject&id=486

When we see a url like this, the request fails with error message
TypeError: must be str, not list

Whether such urls are mistakes or malicious, we should do our best to return a valid page showing the correct canonical url.

**Comment by zh-zhang916** [comment]
I know there are two kinds of URLs. One is like the sample form "/search?lat=xxx&lon =xxx", and another one is with the form "/projects/id/x/y/z". I wonder which one we are using, or we are using both. In this case, what is the correct URL that we should redirect?

**Comment by marlonkeating** [comment]
We use both path arguments and query string arguments.

Path list by page: https://github.com/DemocracyLab/CivicTechExchange/blob/master/common/components/urls/urls_v2.json

We don't have an easy-to-reference canonical list of query strings, but arguments like 'section' are definite relics of our old url system.
