### ISSUE TITLE
Create public feed endpoint for indexing projects

### ISSUE THREAD

**Issue by themightychris** [DemocracyLab/CivicTechExchange#605]
The [brigade-project-index](https://github.com/codeforamerica/brigade-project-index) project aims to index all the civic tech projects in the world, and the data in useful open formats to power better discovery more interconnectivity between civic tech efforts.

The index [supports a number of different feed formats](https://brigade.cloud/projects/crawler/contributing/get-indexed/)

To get DemocracyLab projects into the index, DemocracyLab could either:

- Implement the CSV or JSON projects list format specified in Code for America's [brigade-information repository](https://github.com/codeforamerica/brigade-information#projects-list)
- Expose a new feed format tailored to the data DemocracyLab has to offer. This could just be a direct JSON serialization of DemocracyLab's internal format. A democracylab-specific project capturer/parser will be added to the index's crawler (it's modular and already has 4 formats), so this format can be optimized to capture as much data as DemocracyLab has close to its native format

I recommend the new feed format

**Comment by themightychris** [comment]
jsonschema or its superset openapi would be nice if you want to be thorough, but TBH if you just give us an endpoint we can GET with an array of project objects we can figure out the rest. We're going to capture the entire project resource as-is at our snapshot dataset and extract any mappable fields from that into our index dataset

**Comment by bezunesh** [comment]
@marlonkeating, doesn't the following endpoint already solve this issue ? https://democracylab.org/api/projects

**Comment by PeterBreen** [comment]
Yes, that's the project API endpoint. If that works, great. Please post a new issue if there's changes that you'd need made, but otherwise that is the project API we query ourselves to populate our project pages :)
