### ISSUE TITLE
Profile Links: Link source detection regexes too broad

### ISSUE THREAD

**Issue by marlonkeating** [DemocracyLab/CivicTechExchange#652]
This expression and the other social ones below are a little too generous in matching; for example `https://duckduckgo.com/?q=facebook.com` will result in a Facebook icon on the project profile, despite going to an entirely different site. Not blocking on this PR, I don't think, but we may want an engineering excellence ticket on firming up our autodetect regexes?

_Originally posted by @PeterBreen in https://github.com/DemocracyLab/CivicTechExchange/pull/647#discussion_r648521484_

**Comment by schaferyan** [comment]
Can I work on this?
