### ISSUE TITLE
Incorrect redirect after signing up for newsletter

### ISSUE THREAD

**Issue by bhg** [DemocracyLab/CivicTechExchange#685]
After subscribing to the newsletter, this page appears:

<img width="722" alt="Screen Shot 2021-07-07 at 5 50 55 PM" src="https://user-images.githubusercontent.com/574066/124833493-43a00080-df4c-11eb-8db0-4242ffabcf1a.png">

Clicking "Return to our website" does not link correctly back:

<img width="450" alt="Screen Shot 2021-07-07 at 5 51 24 PM" src="https://user-images.githubusercontent.com/574066/124833584-6af6cd80-df4c-11eb-96aa-2223ca642277.png">

**Comment by yiyichu** [comment]
The issue no longer exists. Clicking "continue to our website" correctly returns to the homepage.

<img width="642" alt="Screen Shot 2023-11-06 at 12 17 40 AM" src="https://github.com/DemocracyLab/CivicTechExchange/assets/83155749/91a9678f-912f-482e-9bb7-4d4aa586bcfb">
