### ISSUE TITLE
Project Profile: Edit Project button is not right-aligned in Admin view

### ISSUE THREAD

**Issue by marlonkeating** [DemocracyLab/CivicTechExchange#698]
In the admin view, The 'Edit Project' button is not bound to the right side of the frame like other neighboring buttons like 'Contact Project', making for a visually inconsistent experience.

![image](https://user-images.githubusercontent.com/322346/126369412-2c76becb-76ac-43ae-bbb3-bacacfc3062c.png)

**Comment by PeterBreen** [comment]
What's happening here is a second `<div>` being wrapped around the buttons, which means the flexbox rules controlling alignment apply to that wrapper div, and therefore not the buttons.

Specifically, the way our buttons in this component normally work is:
```
<div>
  <a class="btn...> /* (actually a react-bootstrap <Button> element, but it renders as an <a>) */
</div>
```

What's happening here is:
```
<div>
  <div>
    <a class="btn...">
  </div>
</div>
```

Removing the extra wrapper div which is around both Edit Project and Contact Project will solve the alignment, though it may be worth investigating removing these extra wrapper divs around _all_ buttons in all views. Some of this code predates our use of react fragments, and it does seem like an opportunity to clean things up. Removing the extra `<div>` and replacing with `<React.Fragment>` seems like a good place to start.

![image](https://user-images.githubusercontent.com/16870466/126375873-8e045b57-b810-424a-a88f-8b2de172808f.png)

https://github.com/DemocracyLab/CivicTechExchange/blob/master/common/components/common/projects/ContactProjectButton.jsx#L188-L191
