### ISSUE TITLE
Few README details and no CONTRIBUTING.md file make it hard to contribute to the project

### ISSUE THREAD

**Issue by lanesawyer** [DemocracyLab/CivicTechExchange#73]
I would love to help contribute to this project, but I'm not sure how to get started.

I might be able to hack my way through all the setup needed to run the site locally, but a fleshed out README and CONTRIBUTING.md would really help me and others interested in contributing get up and running quickly.

**Comment by PeterBreen** [comment]
Added a readme/guide in #75. Please feel free to re-open if there are specifics you think we missed, otherwise thank you for taking the time to add an issue on something DemocracyLab needed to work on :)
