### ISSUE TITLE
Markdown for Project Details - Feature Request

### ISSUE THREAD

**Issue by ddfridley** [DemocracyLab/CivicTechExchange#776]
I really appreciate DemocracyLab and all you do.  I don't want to be a pain but I keep updating the [EnCiv](https://www.democracylab.org/projects/281) project description and I wanted to make this suggestion:

Project leaders can't __format__ the project details or add [links](https://www.democracylab.org/projects/281).  If they could, it would make the project pages more appealing and informative to prospective volunteers.  Markdown, like github uses,  is a great way to support this, and there are lots of packages to support it.

**Comment by marlonkeating** [comment]
Some reference links for the implementation

## Project Profile ##
https://github.com/DemocracyLab/CivicTechExchange/blob/f3b9c83f1e0bf63fd6400d8b1febb8254cd69ba0/common/components/common/projects/AboutProjectDisplay.jsx#L197-L211

## Event Project Profile ##
https://github.com/DemocracyLab/CivicTechExchange/blob/f3b9c83f1e0bf63fd6400d8b1febb8254cd69ba0/common/components/common/event_projects/AboutProjectEventDisplay.jsx#L412

## Group Profile ##
https://github.com/DemocracyLab/CivicTechExchange/blob/f3b9c83f1e0bf63fd6400d8b1febb8254cd69ba0/common/components/common/groups/AboutGroupDisplay.jsx#L126-L128

## Implementation Example ##
https://github.com/DemocracyLab/CivicTechExchange/blob/8fb5d80cc16853e49a9c7b29806170dd95f084ac/common/components/common/projects/RecentActivityCard/TrelloActionCard.jsx#L122

**Comment by ddfridley** [comment]
Thanks. I'll work on this in a few weeks. I'm coding to finish undebate-ssp right now.

**Comment by extreme-coder** [comment]
It seems this issue was already handled by this pull request : https://github.com/DemocracyLab/CivicTechExchange/pull/893.
And it should be closed.

**Comment by PeterBreen** [comment]
You're right; looks to me like #893 meets the request. Closing as completed.
