### ISSUE TITLE
Embeddable, Static Project Lists for Local Brigades

### ISSUE THREAD

**Issue by modelearth** [DemocracyLab/CivicTechExchange#788]
We're creating an easy way for brigades to feature active projects in their websites, with managed Democracy Lab profiles topping the list. We're setting up a static index.html sample in the roof of the CivicTechExchange repo to pull projects by location. Lists will be merged client-side with the Code for America Github project index. Results will be filtered by the Civic Tech Taxonomy, allowing local volunteers to find and integrate related work.

Embedding Development:
https://model.earth/CivicTechExchange/

Current API test page:
https://model.earth/io/template/feed/demolab.html

The javascript frontend will detect the domain and filter the DLab project API call and site template (header, footer and navigation) to match the settings of the current brigade site.

Please update the API to work cross-domain, or adjust the settings to initially include the following domains:

*.codeforamerica.org
*.codeforatlanta.org
*.openseattle.org
*.opensandiego.org
*.codeforall.org
model.earth
neighborhood.org
lifecycle.tools

**Comment by localsite** [comment]
Please also include brigade.cloud, projects.brigade.network and civictechindex.org in the allowed domains.
