### ISSUE TITLE
Contact Group: Update email text 

### ISSUE THREAD

**Issue by marlonkeating** [DemocracyLab/CivicTechExchange#799]
We want to change the text for emails sent when a user contacts a group.

## Headline ##
Add top headline: "Your group has a new message."
## Email Body ##
Change email body to:
"[User Name] has sent the following message to [Group Name]:

""[message]""

To respond, you can reply to this email."

## Code Location ##
https://github.com/DemocracyLab/CivicTechExchange/blob/6c4aeb30c512ce15a82dfdaf733ab31a6e8bf4a3/civictechprojects/views.py#L1114

**Comment by zh-zhang916** [comment]
I may need helps to clarify the term top headline. Does that mean to include "Your group has a new message." into email_subject, or we should make it a header?

**Comment by marlonkeating** [comment]
Yes, it should be a header.
