### ISSUE TITLE
Companies Page - remove Impact Stories

### ISSUE THREAD

**Issue by PeterBreen** [DemocracyLab/CivicTechExchange#819]
As part of a [redesigned companies page](https://trello.com/c/Gk7d4ya2/297-website-companies-page-update-content), we are removing the "Impact Stories" section from both the Hackathon and Sponsorship portions of the page.

- remove the entire Impact Stories section from both sections of the page
- remove the BlogCarousel import statement from the page (don't delete the component, we just don't need to import it here anymore)
- remove `corporate-hackathon-stories` and `corporate-sponsorship-impact` style declarations from the sass partial for this page

relevant files:
 - https://github.com/DemocracyLab/CivicTechExchange/blob/master/common/components/controllers/CorporateHackathonController.jsx (Impact Stories sections start on L269 and L416)
 - https://github.com/DemocracyLab/CivicTechExchange/blob/master/civictechprojects/static/css/partials/_CorporateHackathon.scss

**Comment by ParkerM2** [comment]
I'm interested in working on this Peter.

**Comment by PeterBreen** [comment]
Handling this in the same branch as #822.

**Comment by PeterBreen** [comment]
Done in #827, closing.
