### ISSUE TITLE
Event Profile: Join Event button white text switches to black after clicking

### ISSUE THREAD

**Issue by marlonkeating** [DemocracyLab/CivicTechExchange#839]
When first visiting the Event Profile page, the Join Event button has white text, which is consistent with our design system.  However, after visiting the link pointed to by Join Event the text turns black, which is likely a consequence of the fact that our navigational buttons are styled link anchor tags.

![image](https://user-images.githubusercontent.com/322346/151019436-44ebb911-560e-4c23-b724-5a302cd5ee92.png)

## Code Location ##
https://github.com/DemocracyLab/CivicTechExchange/blob/ff5cff73ec3c0432223a4cdd1dfef92a139b8cf2/common/components/componentsBySection/CreateEvent/AboutEventDisplay.jsx#L188

**Comment by PeterBreen** [comment]
As I mentioned when closing #877 it looks like this was indirectly solved in #868. If further testing shows that's not the case, I'll reopen.
