### ISSUE TITLE
Project's Roles Needed pills display hidden roles

### ISSUE THREAD

**Issue by mfrischmuth** [DemocracyLab/CivicTechExchange#876]
See https://democracylab.org/projects/985. 8 pills are displayed, 3 roles are active and shown in the list, 5 roles are hidden. There should only be 3 project pills displayed corresponding to the unhidden roles.

**Comment by PeterBreen** [comment]
This is a discrepancy between how we render the pills and how we render position entries:

Positions have a conditional filter acting as a check to make sure hidden positions don't show, but the pills do not. 

Compare the function that renders positions (which filter hidden positions):
https://github.com/DemocracyLab/CivicTechExchange/blob/master/common/components/common/projects/AboutProjectDisplay.jsx#L426-L444
to the render function for pills (which does not filter hidden positions):
https://github.com/DemocracyLab/CivicTechExchange/blob/master/common/components/common/projects/AboutProjectDisplay.jsx#L220-L227

To solve this, we need to change it so pills only render entries where `position.isHidden` is false, just like the position entries do.

**Comment by ec-rilo** [comment]
Going to check this out
