### ISSUE TITLE
Companies Page section reordering, content updates

### ISSUE THREAD

**Issue by PeterBreen** [DemocracyLab/CivicTechExchange#888]
Mark asked in Slack that dev do the following to the Companies page. 

for context, this page has two sections of content, "Host a Tech-for-Good Hackathon" and "Sponsor Our Platform & Public Events" hereafter just called Hackathon and Sponsor.

 - In both the Hackathon and Sponsor tab, move the carousel titled "What our partners are saying" above the contact form.
 - In the Hackathon tab, rename "[Read about previous events in our blog](https://github.com/DemocracyLab/CivicTechExchange/blob/master/common/components/controllers/CorporateHackathonController.jsx#L270)" to "Learn more in our blog" and change the hyperlink to https://blog.democracylab.org/how-amazon-hacked-for-good/
 - Leave the blog link in the Sponsors section unchanged.
 - Change the link in `_renderHackathonProspectus()` to the latest version: `2022+DemocracyLab+Corporate+Hackathon+Prospectus.pdf`
 - Change the link in `_renderSponsorProspectus()` to the latest version: `2022+DemocracyLab+Sponsorship+Prospectus.pdf`
 - update section background colors (described below)
 
The page design alternates background color per section. This is manually controlled so we'll have to fix it manually as well: Remove or add the `.corporate-bg-light` class to divs as appropriate, and then the carousel will require some additional work. While the overall section will be grey background, the area inside the border should be white background.
 
 Below the 992px breakpoint, it should look like this:
<img src="https://user-images.githubusercontent.com/16870466/179326899-f812deba-d62a-43b7-83ca-9278e36e2862.png" width="350px" />

Above the 992px breakpoint, it should look like this:
<img src="https://user-images.githubusercontent.com/16870466/179326916-13155489-28b8-47dd-a39a-9deee206779b.png" height="300px" />

Feel free to ask me about this if you get stuck, but I'd start with rules on `.corporate-root .carousel-inner` and `.corporate-root .carousel-item` using media-queries to switch behavior at the correct breakpoint -- however you do it, make sure the changes do not affect the carousel on other pages such as the homepage.

relevant files:
https://github.com/DemocracyLab/CivicTechExchange/blob/master/common/components/controllers/CorporateHackathonController.jsx
https://github.com/DemocracyLab/CivicTechExchange/blob/master/civictechprojects/static/css/partials/_CorporateHackathon.scss

**Comment by schaferyan** [comment]
Can I work on this?

**Comment by PeterBreen** [comment]
> Can I work on this?

Absolutely. Let me know if you've got questions.

**Comment by PeterBreen** [comment]
I've just gotten the links for the updated prospectus documents.  Here's the filenames to use in the cdn.document function:
```
2022+DemocracyLab+Corporate+Hackathon+Prospectus.pdf

2022+DemocracyLab+Sponsorship+Prospectus.pdf
```
