### ISSUE TITLE
Support heroku redis TLS connection

### ISSUE THREAD

**Issue by marlonkeating** [DemocracyLab/CivicTechExchange#897]
Heroku Redis is currently using Redis version 6 which requires a TLS connection.  However, Heroku Redis's self-signed certificates are causing connection issues, and we need to set ssl_cert_reqs=None

## Code Location ##
https://github.com/DemocracyLab/CivicTechExchange/blob/5a0f28ddb62e7dd57ca3baebfcc43f805c807245/common/helpers/queue.py#L8-L10

Instead of initializing redis instance directly from url, we'll need to initialize it with ssl_cert_reqs=None, see below.

## Sample Code ##
From https://devcenter.heroku.com/articles/connecting-heroku-redis#connecting-in-python

```
import os
from urllib.parse import urlparse
import redis

url = urlparse(os.environ.get("REDIS_URL"))
r = redis.Redis(host=url.hostname, port=url.port, username=url.username, password=url.password, ssl=True, ssl_cert_reqs=None)
```

**Comment by Workhqd** [comment]
Could I try to solve this issue? I am not very sure that I could sovle it.
