### ISSUE TITLE
Remove copyright in footer

### ISSUE THREAD

**Issue by mfrischmuth** [DemocracyLab/CivicTechExchange#899]
Creative Commons and Copyright are mutually exclusive. We need to remove the Copyright info from the footer.
![Screenshot 2022-08-19 122351](https://user-images.githubusercontent.com/1594703/185683232-511ac647-d962-4ebc-bb86-fdf16e29a0ac.png)

**Comment by PeterBreen** [comment]
and this just got redesigned and we all missed it 😄 

Simple fix, remove this paragraph in SiteFooter.jsx:
https://github.com/DemocracyLab/CivicTechExchange/blob/5444e6c906d9b7084bd575dd61c55705a5a7a4b4/common/components/chrome/SiteFooter.jsx#L100-L102

Then build and test to make sure it doesn't break layout on mobile, tablet, or desktop size viewports. Unlikely, but better safe than sorry.

**Comment by schaferyan** [comment]
Can I work on this one?
