### ISSUE TITLE
Add Python Auto-formatter

### ISSUE THREAD

**Issue by marlonkeating** [DemocracyLab/CivicTechExchange#905]
We want a python auto-formatter that works similarly to Prettier, our javascript auto-formatter.

## Acceptance Criteria ##
- [x] Compliant with Python standard best practices (like PEP 8)
- [x] Pre-commit git hook (to run python formatting before committing a change)
- [ ] ~~IDE plugins exist for easily formatting on save~~

**Comment by naqeeb** [comment]
Closing this issue as it's been merged. Please re-open if you run into issues.
