### ISSUE TITLE
Add a Reloader for faster updates of rendered pages

### ISSUE THREAD

**Issue by andrewindechemain** [DemocracyLab/CivicTechExchange#927]
Currently, when making changes to the codebase locally a user may need to rebuild the docker container so that the changes take place. We need to install a reloader dependency that instantly makes changes to rendered pages whenever edits are made to the code. Currently, React has adopted react-refresh which works out of the box once installed.

**Comment by AdrielMaximus** [comment]
i tried my best

const ReactRefreshWebpackPlugin = require('@pmmmwh/react-refresh-webpack-plugin');
module.exports = {
  plugins: [
    new ReactRefreshWebpackPlugin()
  ],
  devServer: {
    hot: true,
  },
};

**Comment by PeterBreen** [comment]
this looks like the same issue as described in #477

**Comment by marlonkeating** [comment]
Closing as duplicate of https://github.com/DemocracyLab/CivicTechExchange/issues/477
