### ISSUE TITLE
Volunteer descriptions

### ISSUE THREAD

**Issue by UXBrendan** [DemocracyLab/CivicTechExchange#938]
As an admin for the Orcasound project on the DemocracyLab platform, I have hidden and deleted a select number of positions available. I still receive emails from prospective volunteers for positions that I've hidden or deleted. I know this is a known issue, I just wanted to flag it for prioritization.

**Comment by PeterBreen** [comment]
Hi, sorry about the delay in getting back to you on this but I want to write this up for a volunteer to take. Let me make sure I've got it right, please correct me if I'm wrong:

You have a list of roles for the project, some hidden, some not. A prospective volunteeer clicks "Volunteer With Project" and selects a role that you've hidden or deleted, then emails you? And what you want is for that dropdown of roles to not offer hidden/deleted positions as an option?

**Comment by chunlishao** [comment]
Hi Peter,

You probably right. 

I noticed that there are two ways to apply volunteer positions. One is click the "Apply Now" button under each position, the other is click "Volunteer With Project". 

The dropdown of positions are the same if the project offer positions to apply.

However, when there is no position avaiable, there is no "Apply Now" button, but "Volunteer With Project" enable. 

When volunteer click "Volunteer With Project" button, the dropdown shows all the possible positions in the system. In this way, volunteer can apply an unavailable position.

I guess that is the reason of this issue.

There are two ways to fix it in my opinion.

1. disable/hidden "Volunteer With Project" button when no available positions.
2. show nothing expect "--" in dropdown list, In this way, the "send" button is disabled, and cannot send application.

I perfer the first way. If volunteer do have questions regarding available positions and questions, the "Contact Project" button is for that. 

Any ideas?

**Comment by UXBrendan** [comment]
@PeterBreen  

I apologize for not responding sooner.

I'm not sure what is causing the issue, although @chunlishao may be correct in diagnosing the cause. All I know is that when I don't have any volunteer roles listed for Orcasound, I as the admin still receive volunteer email applications for roles.

**Comment by marlonkeating** [comment]
Opened new issue for implementing this feature request: https://github.com/DemocracyLab/CivicTechExchange/issues/1014
