### ISSUE TITLE
Standardized underline thickness for active tab/nav page

### ISSUE THREAD

**Issue by PeterBreen** [DemocracyLab/CivicTechExchange#959]
We have both tabbed content and site navigation which uses a brand color orange underline to indicate the active section/page. See, for example, the "I'd like to..." section on the homepage:
![image](https://user-images.githubusercontent.com/16870466/229636204-a2777b32-407c-48b6-adce-4dfcbc793fa0.png)
(Volunteer section content shown)

and the site nav, telling the user they are on the Home page:

![image](https://user-images.githubusercontent.com/16870466/229636314-607f42b7-94e0-4d0d-ac46-b0122815022d.png)

However, the thickness of this underline is inconsistent across our various components, and our accessibility designers would like it to be both consistent and 4px.

Therefore,
 - change homepage tabs component to have 4px underline on active section (currently 3px)
 - change site navigation component to have 4px underline on current page (currently 1px)

For the nav, `text-decoration-thickness: 4px;` should do it. See [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration-thickness) and [caniuse](https://caniuse.com/?search=text-decoration-thickness) for this property -- we're good.

For the tabbed content on the homepage, change this from -3 to -4px.
https://github.com/DemocracyLab/CivicTechExchange/blob/master/civictechprojects/static/css/partials/_LandingController.scss#L59

**Comment by manisha-borkar** [comment]
@PeterBreen I would like to take this issue. Can you please assign it to me @manisha-borkar?
