### ISSUE TITLE
Remove references to EMAIL_HOST_PASSWORD

### ISSUE THREAD

**Issue by marlonkeating** [DemocracyLab/CivicTechExchange#976]
We're no longer using the EMAIL_HOST_PASSWORD environment variable, and so references to it should be removed from our documentation and setup scripts.

Search Query:
https://github.com/search?q=repo%3ADemocracyLab%2FCivicTechExchange%20EMAIL_HOST_PASSWORD&type=code

**Comment by 2div** [comment]
Hi , I would like to try ans solve this task, kindly assign it to me if not handled by anyone else?

what i understood is that you want to remove EMAIL_HOST_PASSWORD environment variable, and this variable is in 3 files according to above search query.
files are  app.json , example.env and democracylab_environment_variables.sh
To solve the task , i will delete the variable from these 3 files only.
Please confirm if that is the required solution.
Thank you

**Comment by ddfridley** [comment]
closed by #1063
