### ISSUE TITLE
[High Priority]No verify email after new user sign up

### ISSUE THREAD

**Issue by chunlishao** [DemocracyLab/CivicTechExchange#993]
Someone request to me on Linkedin. She did not receive any verfy email after sign up on Democracylab.org and it blocked her apply the volunteer position.

I tried to sign up a new account and did not receive any verify email either.

**Comment by chunlishao** [comment]
From Marlon: There was an issue with the new Redis provider we transferred to during the last release, that was preventing emails from being sent out.  I've switched to another Redis provider, which seems to be working.  Going to check and see if there's a way to recover the emails that weren't sent out successfully.

**Comment by Janechj** [comment]
I still can't receive any verify email.

**Comment by marlonkeating** [comment]
Issue hasn't been reproduced in a while, so closing for now.
